---
- name: Pull Docker Image from Docker Hub
  hosts: localhost
  connection: local
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "vikash04/calculator-app"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result
        
    - name: Ensure Docker is running (Mac workaround)
      command: "open -a Docker"
      args:
        creates: "/var/run/docker.sock"
      when: ansible_os_family == "Darwin"  # Runs only on Mac

    - name: Running container
      docker_container:
        name: calculator
        image: vikash04/calculator-app
        state: started
        detach: true
        interactive: true