---
- name: Deploy Calculator App
  hosts: localhost
  connection: local
  tasks:
    - name: Pull Docker Image
      docker_image:
        name: "vikash04/calculator-app"
        source: pull
      register: docker_pull_result

    - name: Display Docker Pull Result
      debug:
        var: docker_pull_result

    - name: Run Calculator Container
      docker_container:
        name: calculator
        image: vikash04/calculator-app
        state: started
        detach: true
        interactive: true